#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NWFlYzljNWIzNTMyMjRkOGZhY2JkMmRkNDMzODgwNmU3YTQ4MGMwNDJmYzYyYTY3ZDE1NjBhNWFjNmJmMzgxNWUzZTczZTRmNDkxMzIwYWYzODE1ZGYzNzI3YjBkYTQ3NmM4OWY4YTUyNTAxMDMwZmM1OTk0ZTdjM2JjNmIzYTE=
  logging:
    logstash: # forward logs to ELK
      enabled: true
      host: jhipster-logstash
  metrics:
    logs: # report metrics in the logs
      enabled: true
      report-frequency: 60 # in seconds

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
